services:
  web:
    build: .
    ports: 
      - "5000:5000"  
    depends_on:
      - db
    env_file:
      - app.env
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - db.env